name: Build Angular App

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout ğŸ˜
        uses: actions/checkout@v5.0.0

      - name: Setup Node ğŸŒ
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 18.x

      - name: Install ğŸ¤–
        run: |
          npm ci
          ng build --base-href /

      - name: Angular Deploy gh-pages Actions
        # You may pin to the exact commit or the version.
        # uses: AhsanAyaz/angular-deploy-gh-pages-actions@2272ef32f364bc80d8680ee03d8e58f126156c31
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GIT_TOKEN }}
          angular_dist_build_folder: docs
          
